apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      serviceAccountName: monitoring
      containers:
        - name: web-server
          image: nginx
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: homework-volume
              mountPath: /homework
          # Для задания с * может потребоваться дополнительная настройка
      volumes:
        - name: homework-volume
          persistentVolumeClaim:
            claimName: my-pvc
